version: '3.4'
services:
  app:
    container_name: 'api_rent_car'
    build: .
    network_mode: host
    environment:
    - PORT=4001
    - HOST=localhost
    - DATABASE_HOST=localhost
    - DATABASE_NAME=rent_car_binar
    - DATABASE_USER=postgres
    - DATABASE_PASSWORD=admin
    - DATABASE_PORT=5432
    - REDIS_PORT=6399
    - REDIS_HOST=redis
    - CLOUDINARY_NAME=dnvltueqb
    - CLOUDINARY_API_KEY=131712519741951
    - CLOUDINARY_API_SECRET=hj0ZgOKOwG8l5o8vpnSwPtR6US0
    - SECRET_KEY=120wosdoowe0112nn0p9wd12n1212enpj
    - MAILER_SMTP_HOST=smtp.mailtrap.io
    - MAILER_SMTP_PORT=465
    - MAILER_SECURE=false
    - MAILER_AUTH_USER=e7944463ded79f
    - MAILER_AUTH_PASSWORD=e2d82fa7b1e8f9
    - MAILER_SENDER_NAME= binarcarrent
    - MAILER_SENDER_EMAIL= noreaplybinarcarrent@mail.com
    command: npm start
  redis:
    container_name: 'redis'
    image: redis
    ports:
    - "6399:6399"
